name: Build and Deploy app

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest

    steps:
      - name: Clonage du code
        uses: actions/checkout@v4

      - name: installation de go
        uses: actions/setup-go@v4

      - name: Crée l'exécutable et 
        run: | 
              go build -o mysuperapp main.go

      - name: Met l'exécutable dans un zip
        run: zip mysuperapp.zip mysuperapp

      - name: Upload l'artefact (le zip)
        uses: actions/upload-artifact@v4
        with:
          name: mysuperapp
          path: mysuperapp.zip


  deploy:
    name: Déploiement
    needs: build
    runs-on: self-hosted

    steps:
      - name: Télécharge l'artefact(le zip contenant l'executable)
        uses: actions/download-artifact@v4
        with: 
          name: mysuperapp
    
        
      - name: Vérifie les fichiers téléchargés
        run: ls -al
  
      - name: Crée le dossier du déploy..
        run : mkdir -p ~/apps/
  
      - name: Déploiement
        run: |
            mv mysuperapp.zip ~/apps/
            unzip -o ~/apps/mysuperapp.zip -d ~/apps/
            rm ~/apps/mysuperapp.zip

