name: Build and Deploy app

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest

    steps:
      - name: Clonage du code
        uses: actions/checkout@v4

      - name: installation de go
        uses: actions/setup-go@v4

      - name: Crée l'exécutable et 
        run: | 
              go build -o mysuperapp main.go

      - name: Met l'exécutable dans un zip
        run: zip mysuperapp.zip mysuperapp

      - name: Upload l'artefact (le zip)
        uses: actions/upload-artifact@v4
        with:
          name: mysuperapp
          path: mysuperapp.zip


  deploy:
    name: Déploiement
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Télécharge l'artefact(le zip contenant l'executable)
        uses: actions/download-artifact@v4
        with: 
          name: mysuperapp
        
      - name: Setup ssh
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

      - name: Deploiement 
        run: |
             scp mysuperapp.zip ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}
             ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "unzip -o ${{ secrets.DEPLOY_PATH }}/mysuperapp.zip -d ${{ secrets.DEPLOY_PATH }} && rm ${{ secrets.DEPLOY_PATH }}/mysuperapp.zip"

          


 